### PR TITLE
Add component rpc-openstack release r16.2.9

### PR DESCRIPTION
**Pull request by cjloader**

### CODE REVIEW

**Comment by cjloader** [comment]
Please start once https://github.com/rcbops/rpc-openstack/pull/3458 merges. Thanks.

**Comment by antonym** [comment]
:shipit:

**Comment by antonym** [comment]
recheck_release

**Comment by antonym** [comment]
recheck_release

**Comment by antonym** [comment]
:shipit:

**Comment by odyssey4me** [comment]
:shipit:

**Comment by odyssey4me** [comment]
The release is failing because the SHA releasing has not yet had a successful MNAIO build. It is trying to do a build to validate it, but failing due to timeout.

https://github.com/rcbops/rpc-gating/pull/1292 will correct the timeout

Meanwhile, 
https://rpc.jenkins.cit.rackspace.net/view/RPC-O/job/PM_rpc-openstack-pike-xenial_mnaio_no_artifacts-swift-deploy/338 will hopefully complete successfully. If it does, we can retry the release and it should find that success and complete the release.

**Comment by odyssey4me** [comment]
https://rpc.jenkins.cit.rackspace.net/view/RPC-O/job/PM_rpc-openstack-pike-xenial_mnaio_no_artifacts-swift-deploy/338/ just passed, so this should just work now.

**Comment by odyssey4me** [comment]
:shipit:

**Pull request merged**
