### PR TITLE
Add rpc-ceph 1.1.11 release

### PR DESCRIPTION
**Pull request by mvollman**

### CODE REVIEW

**Comment by mvollman** [comment]
:shipit:

**Comment by dealako** [comment]
recheck_release

**Comment by dealako** [comment]
recheck_all

**Comment by hughsaunders** [comment]
This looks like a genuine failure: https://rpc.jenkins.cit.rackspace.net/blue/organizations/jenkins/RELEASE_rpc-ceph-master-xenial-keystone_rgw-test/detail/RELEASE_rpc-ceph-master-xenial-keystone_rgw-test/11/pipeline

**Comment by mvollman** [comment]
recheck_all

**Comment by mvollman** [comment]
recheck_release

**Comment by mvollman** [comment]
:shipit:

**Pull request merged**
