### PR TITLE
Add component rpc-openstack release r14.20.0

### PR DESCRIPTION
**Pull request by Frank-ZhangXin**
Update newton release.
version r14.20.0
sha 912f5809689e82f5fcd5ea843f6f698eefb56991
(https://rpc.jenkins.cit.rackspace.net/user/chun1772/my-views/view/Newton/job/PM_rpc-openstack-newton-xenial_mnaio_loose_artifacts-swift-deploy/352/)

### CODE REVIEW

**Comment by Frank-ZhangXin** [comment]
:shipit:

**Comment by chundu** [comment]
:shipit:

**Comment by dealako** [comment]
:shipit: skip validation

**Comment by dealako** [comment]
:shipit: skip validation

**Comment by dealako** [comment]
:shipit: skip validation

**Comment by dealako** [comment]
:recheck all:

**Pull request merged**
