### PR TITLE
Add rpc-upgrades 1.1.5 release

### PR DESCRIPTION
**Pull request by antonym**
Add rpc-upgrades 1.1.5 release

### CODE REVIEW

**Comment by antonym** [comment]
:shipit:

**Comment by odyssey4me** [comment]
:shipit:

**Comment by antonym** [comment]
Liberty_to_Newton failed while Mitaka_to_Newton passed:

https://rpc.jenkins.cit.rackspace.net/view/Upgrades/job/RELEASE_rpc-upgrades-master-trusty_aio-swift-liberty_to_newton_leap/2/consoleText

It failed after successful completion of Leapfrog during the MaaS verify phase.  I recently upgraded MaaS to the latest release and have been seeing a random race condition in MaaS verify over the last week.  This should be good to go ahead and publish and I'll try and chase down this verify issue with the MaaS team.

```
fatal: [aio1]: FAILED! => {"changed": false, "cmd": ["/openstack/venvs/maas-1.7.5/bin/python", "/opt/rpc-maas-tools/rpc-maas-tool.py", "--logfile", "/var/lib/jenkins/workspace/RELEASE_rpc-upgrades-master-trusty_aio-swift-liberty_to_newton_leap/artifacts/rpc-maas-logs.txt", "verify-local"], "delta": "0:00:08.124041", "end": "2018-09-04 23:09:53.372328", "failed": true, "rc": 1, "start": "2018-09-04 23:09:45.248287", "stderr": "", "stdout": "The following metrics are required by alarms but not produced by any checks: set(['glance_registry_local_status', 'nova-compute_status', 'nova-consoleauth_status', 'neutron_api_local_status', 'nova_api_local_status', 'neutron-l3-agent_status', 'neutron-linuxbridge-agent_status', 'neutron-dhcp-agent_status', 'cloud_resource_used_memory', 'cinder-scheduler_status', 'nova-scheduler_status', 'glance_api_local_status', 'nova-cert_status', 'cinder-volume-lvm_status', 'cinder_api_local_status', 'neutron-metering-agent_status', 'cloud_resource_total_memory', 'neutron-metadata-agent_status', 'heat_api_local_status', 'nova-conductor_status'])\nThe following checks failed to execute or didn't return 'okay' as their status: [('neutron_linuxbridge_agent_check--aio1', \"/openstack/venvs/maas-1.7.5/local/lib/python2.7/site-packages/keystoneauth1/adapter.py:200: UserWarning: Using keystoneclient sessions has been deprecated. Please update your software to use keystoneauth1.\\n  warnings.warn('Using keystoneclient sessions has been deprecated. '\\
```

**Comment by antonym** [comment]
recheck_release

**Comment by antonym** [comment]
:shipit:

**Comment by git-harry** [comment]
I've updated the hash in the commit to reflect the actual one used when this was manually released yesterday.

**Pull request merged**
