### PR TITLE
add component release 1.0.7

### PR DESCRIPTION
**Pull request by hughsaunders**

### CODE REVIEW

**Comment by hughsaunders** [comment]
:shipit:

**Comment by odyssey4me** [comment]
:shipit:

**Comment by hughsaunders** [comment]
:shipit:

**Comment by hughsaunders** [comment]
test

**Comment by hughsaunders** [comment]
:shipit:

**Comment by hughsaunders** [comment]
:shipit:

**Comment by hughsaunders** [comment]
:shipit:

**Comment by hughsaunders** [comment]
:shipit:

**Pull request merged**
